# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_text',
            field=models.TextField(default='This is a preview of an article'),
            preserve_default=False,
        ),
    ]
