# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_preview_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='preview_text',
        ),
    ]
