# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160615_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 26, 15, 15, 3, 73043)),
            preserve_default=False,
        ),
    ]
