# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20160823_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_alias',
            field=models.SlugField(unique=True),
        ),
    ]
