# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20160823_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_alias',
            field=models.SlugField(unique=True),
        ),
    ]
