# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_article_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_alias',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
