# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20160825_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.CharField(choices=[(1, 'Not Published'), (2, 'Staged for publication'), (3, 'Published')], default=1, max_length=1),
        ),
    ]
