# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_article_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='article',
            name='state',
            field=models.CharField(choices=[('1', 'Not Published'), ('2', 'Staged for publication'), ('3', 'Published')], default=1, max_length=1),
        ),
    ]
